/******************************************************************************
 * Copyright (c) 2024-2025.                                                   *
 * valo.media GmbH                                                            *
 * All rights reserved.                                                       *
 ******************************************************************************/

//
//  build.gradle.kts
//  Tower_Android
//


/*
 * Top-level build file with configuration options common to all sub-projects/modules.
 */

import java.util.Properties

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.hilt.android) apply false
    alias(libs.plugins.devtools.ksp) apply false
}

allprojects {
    tasks.withType<JavaCompile>().configureEach {
        // Show warnings about deprecated features.
        options.isDeprecation = true
    }

}

tasks.wrapper {
    // Use the gradle version pinned in gradle/wrapper/gradle-wrapper.properties.
    //
    // That file is the single source of truth for the gradle version, and the only wrapper file
    // that is checked in: it is plain text, so it stays reviewable, and renovate keeps it fresh
    // through its gradle-wrapper manager. The wrapper jar and scripts stay untracked and are
    // regenerated by this task.
    //
    // This task is pulled in as a dependency by :app:preBuild, to ensure the wrapper is always
    // up-to-date with the desired version of gradle. Deriving the version here rather than
    // hard-coding it keeps that regeneration from silently re-pinning gradle to whichever
    // version happens to be running the task.
    val wrapperProperties = file("gradle/wrapper/gradle-wrapper.properties")
    val distributionUrl = wrapperProperties
        .takeIf { it.isFile }
        ?.let { file -> Properties().apply { file.reader().use(::load) } }
        ?.getProperty("distributionUrl")
        ?: error("$wrapperProperties must exist and define distributionUrl.")
    val distribution = Regex("""gradle-(.+?)-(bin|all)\.zip""").find(distributionUrl)
        ?: error("Cannot read the gradle version from distributionUrl: $distributionUrl")
    gradleVersion = distribution.groupValues[1]
    distributionType = when (distribution.groupValues[2]) {
        "all" -> Wrapper.DistributionType.ALL
        else -> Wrapper.DistributionType.BIN
    }
}
